dist: xenial
language: python

cache:
  directories:
    - $HOME/.cache/pip
    # OS X cache not yet enabled: https://github.com/travis-ci/travis-ci/issues/4011
    - $HOME/Library/Caches/pip
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - python: 3.8
      env: TOXENV=pep8
    - python: 3.8
      env: TOXENV=docs
      addons:
        apt:
          packages:
            - libenchant-dev
            - graphviz

install:
  - pip install virtualenv wheel
  - pip install -U pip
  - python -m virtualenv ~/.venv
  - source ~/.venv/bin/activate
  - pip install tox codecov


script:
  - source ~/.venv/bin/activate
  - tox

after_success:
  - ./.travis/upload_coverage.sh

after_script:
  - cat .tox/$TOXENV/log/$TOXENV-*.log
